import pytest
from backend.app.generators import generer_iac

def test_generer_vsphere_vm():
    demande = {
        "resource_type": "vm",
        "platform": "vsphere",
        "cpu": 4,
        "ram_gb": 8,
        "storage_gb": 50,
        "image": "ubuntu-22.04",
        "network": "VM Network"
    }
    resultat = generer_iac(demande)
    
    assert resultat["type"] == "terraform-vsphere"
    assert len(resultat["fichiers"]) == 2
    assert "main.tf" in resultat["contenu"]
    assert "variables.tf" in resultat["contenu"]
    
    tf_content = resultat["contenu"]["main.tf"]
    assert "resource \"vsphere_virtual_machine\"" in tf_content
    assert "num_cpus = 4" in tf_content
    assert "memory   = 8192" in tf_content
    assert "size             = 50" in tf_content
    assert "annotation = \"Generated by IaC Chatbot | image=ubuntu-22.04\"" in tf_content

def test_generer_openshift_container():
    demande = {
        "resource_type": "container",
        "platform": "openshift",
        "cpu": 1,
        "ram_gb": 2,
        "storage_gb": 20,
        "image": "postgres:15"
    }
    resultat = generer_iac(demande, namespace="test-ns")
    
    assert resultat["type"] == "container-openshift"
    assert len(resultat["fichiers"]) == 1
    
    # Récupérer la première clé du dict contenu (le fichier .yaml)
    nom_fichier = list(resultat["contenu"].keys())[0]
    yaml_content = resultat["contenu"][nom_fichier]
    
    assert "kind: Deployment" in yaml_content
    assert "kind: Service" in yaml_content
    assert "kind: PersistentVolumeClaim" in yaml_content
    assert "namespace: test-ns" in yaml_content
    assert "image: postgres:15" in yaml_content
    assert "containerPort: 5432" in yaml_content # Déduit automatiquement par deduire_config_image

def test_generer_kubevirt_vm():
    demande = {
        "resource_type": "vm",
        "platform": "openshift",
        "cpu": 2,
        "ram_gb": 4,
        "storage_gb": 30,
        "image": "centos-stream:9",
        "network": "default"
    }
    resultat = generer_iac(demande, namespace="test-ns")
    
    assert resultat["type"] == "kubevirt-openshift"
    
    nom_fichier = list(resultat["contenu"].keys())[0]
    yaml_content = resultat["contenu"][nom_fichier]
    
    assert "apiVersion: kubevirt.io/v1" in yaml_content
    assert "kind: VirtualMachine" in yaml_content
    assert "cores: 2" in yaml_content
    assert "memory: \"4Gi\"" in yaml_content
    assert "storage: 30Gi" in yaml_content

def test_generer_invalid_combination():
    demande = {
        "resource_type": "container",
        "platform": "vsphere",
        "cpu": 1,
        "ram_gb": 2,
        "storage_gb": 20,
        "image": "nginx:latest"
    }
    # Théoriquement bloqué par Pydantic avant, mais on teste le garde-fou du générateur
    with pytest.raises(ValueError):
        generer_iac(demande)
